// resources/js/Shared/Nav.vue
<script setup>
import NavLink from '@/Shared/NavLink.vue'
</script>

<template>
  <section class="p-4 bg-gray-800 drop-shadow-md">
    <header class="flex justify-between">
      <h1 class="text-lg mt-1 text-slate-200">Logo</h1>
      <section class="flex space-x-4">
        <NavLink :active="$page.component === 'Home'" href="/">Home</NavLink>
        <NavLink :active="$page.component === 'Resume'" href="/resume">Resume</NavLink>
      </section>
      <section>
        <Link href="https://github.com/aileks">
          <img alt="Github" class="max-w-6 mt-1" src="../../../public/images/github-mark-white.png"/>
        </Link>
      </section>
    </header>
  </section>
</template>

// src/app/components/nav.tsx
import Link from 'next/link';

export default function Nav() {
  return (
    <nav className="flex justify-between h-10 bg-gray-100 text-black">
      <img className="w-[24px] h-[24px] ml-2 self-center" src="logo.png" />

      <section className="flex justify-end space-x-4 items-center mr-4">
        <Link
          className="hover:underline hover:text-gray-700 hover:italic"
          href="/"
        >
          Home
        </Link>

        <Link
          className="hover:underline hover:text-gray-700 hover:italic"
          href="/about"
        >
          About
        </Link>

        <Link
          className="hover:underline hover:text-gray-700 hover:italic"
          href="/projects"
        >
          Projects
        </Link>
      </section>
    </nav>
  );
}
